...

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -4,31 +4,31 @@
 
 cd build
 echo "$PWD"
-#cmake -D HIPS_BUILD_TESTS=ON -D REACTIONS_ENABLED=ON..
-#make -j
-#make install
-#cd ../run
-#
-#############################
-#
-#echo ""
-#echo "******** Running test.x"
-#echo ""
-#./test.x
-#if [ $? -ne 0 ]; then
-#  echo "TEST FAILED, ABORT"
-#  exit 1
-#fi
-#
-#############################
-#
-#echo ""
-#echo "******** Running test_rxn.x"
-#echo ""
-#./test_rxn.x
-#if [ $? -ne 0 ]; then
-#  echo "TEST FAILED, ABORT"
-#  exit 1
-#fi
+cmake -D HIPS_BUILD_TESTS=ON -D REACTIONS_ENABLED=ON..
+make -j
+make install
+cd ../run
+
+############################
+
+echo ""
+echo "******** Running test.x"
+echo ""
+./test.x
+if [ $? -ne 0 ]; then
+  echo "TEST FAILED, ABORT"
+  exit 1
+fi
+
+############################
+
+echo ""
+echo "******** Running test_rxn.x"
+echo ""
+./test_rxn.x
+if [ $? -ne 0 ]; then
+  echo "TEST FAILED, ABORT"
+  exit 1
+fi
 
 
